import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  mainContainer: { flex: 1, backgroundColor: "#f7fafc" },
  header: {
    height: 60,
    backgroundColor: "#2b6cb0",
    justifyContent: "center",
    alignItems: "center",
    paddingTop: 15,
  },
  headerTitle: { color: "#fff", fontSize: 18, fontWeight: "bold" },
  tabBar: {
    flexDirection: "row",
    backgroundColor: "#edf2f7",
    borderBottomWidth: 1,
    borderColor: "#cbd5e0",
  },
  tabButton: { flex: 1, paddingVertical: 12, alignItems: "center" },
  activeTab: {
    backgroundColor: "#fff",
    borderBottomWidth: 3,
    borderBottomColor: "#2b6cb0",
  },
  tabLabel: { fontSize: 13, fontWeight: "600", color: "#4a5568" },
  activeTabText: { color: "#2b6cb0", fontWeight: "bold" },
  body: { flex: 1, padding: 15 },
  taskContainer: { padding: 10 },
  taskTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#2d3748",
    marginBottom: 15,
  },
  input: {
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#cbd5e0",
    padding: 12,
    borderRadius: 6,
    marginBottom: 12,
    fontSize: 15,
    color: "#2d3748",
  },
  bold: { fontWeight: "bold" },
  card: {
    marginTop: 20,
    padding: 15,
    backgroundColor: "#ebf8ff",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#bee3f8",
  },
  cardTitle: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#2b6cb0",
    marginBottom: 8,
  },
  cardText: { fontSize: 14, color: "#2d3748", marginVertical: 2 },
  resultBox: {
    marginTop: 20,
    padding: 15,
    backgroundColor: "#e6fffa",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#b2f5ea",
  },
  resultText: { fontSize: 15, color: "#234e52" },
  sequenceText: {
    fontSize: 14,
    color: "#234e52",
    marginTop: 8,
    lineHeight: 22,
  },
});
